name: Publish SEOLinkMap MCP Server to Registry

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  validate-and-publish:
    name: Validate and Publish MCP Server
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Install validation tools
        run: npm install -g ajv-cli

      - name: Update server version from tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            jq --arg v "$VERSION" '.version_detail.version = $v' server.json > tmp && mv tmp server.json
            echo "Updated to version: $VERSION"
          fi

      - name: Validate server.json
        run: |
          curl -o server.schema.json https://static.modelcontextprotocol.io/schemas/2025-07-09/server.schema.json
          ajv validate -s server.schema.json -d server.json

      - name: Install MCP Publisher
        run: |
          curl -L "https://github.com/modelcontextprotocol/registry/releases/download/v1.0.0/mcp-publisher_1.0.0_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz" | tar xz mcp-publisher

      - name: Login to MCP Registry
        run: |
          ./mcp-publisher login dns --domain seolinkmap.com --private-key "${{ secrets.MCP_PRIVATE_KEY }}"

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish --file server.json
